/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace io.kubernetes.csharp.Model
{
    /// <summary>
    /// StatefulSetStatus represents the current state of a StatefulSet.
    /// </summary>
    [DataContract]
    public partial class V1beta1StatefulSetStatus :  IEquatable<V1beta1StatefulSetStatus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1beta1StatefulSetStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1beta1StatefulSetStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1beta1StatefulSetStatus" /> class.
        /// </summary>
        /// <param name="ObservedGeneration">most recent generation observed by this autoscaler..</param>
        /// <param name="Replicas">Replicas is the number of actual replicas. (required).</param>
        public V1beta1StatefulSetStatus(long? ObservedGeneration = default(long?), int? Replicas = default(int?))
        {
            // to ensure "Replicas" is required (not null)
            if (Replicas == null)
            {
                throw new InvalidDataException("Replicas is a required property for V1beta1StatefulSetStatus and cannot be null");
            }
            else
            {
                this.Replicas = Replicas;
            }
            this.ObservedGeneration = ObservedGeneration;
        }
        
        /// <summary>
        /// most recent generation observed by this autoscaler.
        /// </summary>
        /// <value>most recent generation observed by this autoscaler.</value>
        [DataMember(Name="observedGeneration", EmitDefaultValue=false)]
        public long? ObservedGeneration { get; set; }
        /// <summary>
        /// Replicas is the number of actual replicas.
        /// </summary>
        /// <value>Replicas is the number of actual replicas.</value>
        [DataMember(Name="replicas", EmitDefaultValue=false)]
        public int? Replicas { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1beta1StatefulSetStatus {\n");
            sb.Append("  ObservedGeneration: ").Append(ObservedGeneration).Append("\n");
            sb.Append("  Replicas: ").Append(Replicas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as V1beta1StatefulSetStatus);
        }

        /// <summary>
        /// Returns true if V1beta1StatefulSetStatus instances are equal
        /// </summary>
        /// <param name="other">Instance of V1beta1StatefulSetStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1beta1StatefulSetStatus other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ObservedGeneration == other.ObservedGeneration ||
                    this.ObservedGeneration != null &&
                    this.ObservedGeneration.Equals(other.ObservedGeneration)
                ) && 
                (
                    this.Replicas == other.Replicas ||
                    this.Replicas != null &&
                    this.Replicas.Equals(other.Replicas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ObservedGeneration != null)
                    hash = hash * 59 + this.ObservedGeneration.GetHashCode();
                if (this.Replicas != null)
                    hash = hash * 59 + this.Replicas.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
