/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace io.kubernetes.csharp.Model
{
    /// <summary>
    /// specification of a horizontal pod autoscaler.
    /// </summary>
    [DataContract]
    public partial class V1beta1HorizontalPodAutoscalerSpec :  IEquatable<V1beta1HorizontalPodAutoscalerSpec>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1beta1HorizontalPodAutoscalerSpec" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1beta1HorizontalPodAutoscalerSpec() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1beta1HorizontalPodAutoscalerSpec" /> class.
        /// </summary>
        /// <param name="CpuUtilization">target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified it defaults to the target CPU utilization at 80% of the requested resources..</param>
        /// <param name="MaxReplicas">upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas. (required).</param>
        /// <param name="MinReplicas">lower limit for the number of pods that can be set by the autoscaler, default 1..</param>
        /// <param name="ScaleRef">reference to Scale subresource; horizontal pod autoscaler will learn the current resource consumption from its status, and will set the desired number of pods by modifying its spec. (required).</param>
        public V1beta1HorizontalPodAutoscalerSpec(V1beta1CPUTargetUtilization CpuUtilization = default(V1beta1CPUTargetUtilization), int? MaxReplicas = default(int?), int? MinReplicas = default(int?), V1beta1SubresourceReference ScaleRef = default(V1beta1SubresourceReference))
        {
            // to ensure "MaxReplicas" is required (not null)
            if (MaxReplicas == null)
            {
                throw new InvalidDataException("MaxReplicas is a required property for V1beta1HorizontalPodAutoscalerSpec and cannot be null");
            }
            else
            {
                this.MaxReplicas = MaxReplicas;
            }
            // to ensure "ScaleRef" is required (not null)
            if (ScaleRef == null)
            {
                throw new InvalidDataException("ScaleRef is a required property for V1beta1HorizontalPodAutoscalerSpec and cannot be null");
            }
            else
            {
                this.ScaleRef = ScaleRef;
            }
            this.CpuUtilization = CpuUtilization;
            this.MinReplicas = MinReplicas;
        }
        
        /// <summary>
        /// target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified it defaults to the target CPU utilization at 80% of the requested resources.
        /// </summary>
        /// <value>target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified it defaults to the target CPU utilization at 80% of the requested resources.</value>
        [DataMember(Name="cpuUtilization", EmitDefaultValue=false)]
        public V1beta1CPUTargetUtilization CpuUtilization { get; set; }
        /// <summary>
        /// upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas.
        /// </summary>
        /// <value>upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas.</value>
        [DataMember(Name="maxReplicas", EmitDefaultValue=false)]
        public int? MaxReplicas { get; set; }
        /// <summary>
        /// lower limit for the number of pods that can be set by the autoscaler, default 1.
        /// </summary>
        /// <value>lower limit for the number of pods that can be set by the autoscaler, default 1.</value>
        [DataMember(Name="minReplicas", EmitDefaultValue=false)]
        public int? MinReplicas { get; set; }
        /// <summary>
        /// reference to Scale subresource; horizontal pod autoscaler will learn the current resource consumption from its status, and will set the desired number of pods by modifying its spec.
        /// </summary>
        /// <value>reference to Scale subresource; horizontal pod autoscaler will learn the current resource consumption from its status, and will set the desired number of pods by modifying its spec.</value>
        [DataMember(Name="scaleRef", EmitDefaultValue=false)]
        public V1beta1SubresourceReference ScaleRef { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1beta1HorizontalPodAutoscalerSpec {\n");
            sb.Append("  CpuUtilization: ").Append(CpuUtilization).Append("\n");
            sb.Append("  MaxReplicas: ").Append(MaxReplicas).Append("\n");
            sb.Append("  MinReplicas: ").Append(MinReplicas).Append("\n");
            sb.Append("  ScaleRef: ").Append(ScaleRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as V1beta1HorizontalPodAutoscalerSpec);
        }

        /// <summary>
        /// Returns true if V1beta1HorizontalPodAutoscalerSpec instances are equal
        /// </summary>
        /// <param name="other">Instance of V1beta1HorizontalPodAutoscalerSpec to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1beta1HorizontalPodAutoscalerSpec other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CpuUtilization == other.CpuUtilization ||
                    this.CpuUtilization != null &&
                    this.CpuUtilization.Equals(other.CpuUtilization)
                ) && 
                (
                    this.MaxReplicas == other.MaxReplicas ||
                    this.MaxReplicas != null &&
                    this.MaxReplicas.Equals(other.MaxReplicas)
                ) && 
                (
                    this.MinReplicas == other.MinReplicas ||
                    this.MinReplicas != null &&
                    this.MinReplicas.Equals(other.MinReplicas)
                ) && 
                (
                    this.ScaleRef == other.ScaleRef ||
                    this.ScaleRef != null &&
                    this.ScaleRef.Equals(other.ScaleRef)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CpuUtilization != null)
                    hash = hash * 59 + this.CpuUtilization.GetHashCode();
                if (this.MaxReplicas != null)
                    hash = hash * 59 + this.MaxReplicas.GetHashCode();
                if (this.MinReplicas != null)
                    hash = hash * 59 + this.MinReplicas.GetHashCode();
                if (this.ScaleRef != null)
                    hash = hash * 59 + this.ScaleRef.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
