/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace io.kubernetes.csharp.Model
{
    /// <summary>
    /// V1beta1CPUTargetUtilization
    /// </summary>
    [DataContract]
    public partial class V1beta1CPUTargetUtilization :  IEquatable<V1beta1CPUTargetUtilization>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1beta1CPUTargetUtilization" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1beta1CPUTargetUtilization() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1beta1CPUTargetUtilization" /> class.
        /// </summary>
        /// <param name="TargetPercentage">fraction of the requested CPU that should be utilized/used, e.g. 70 means that 70% of the requested CPU should be in use. (required).</param>
        public V1beta1CPUTargetUtilization(int? TargetPercentage = default(int?))
        {
            // to ensure "TargetPercentage" is required (not null)
            if (TargetPercentage == null)
            {
                throw new InvalidDataException("TargetPercentage is a required property for V1beta1CPUTargetUtilization and cannot be null");
            }
            else
            {
                this.TargetPercentage = TargetPercentage;
            }
        }
        
        /// <summary>
        /// fraction of the requested CPU that should be utilized/used, e.g. 70 means that 70% of the requested CPU should be in use.
        /// </summary>
        /// <value>fraction of the requested CPU that should be utilized/used, e.g. 70 means that 70% of the requested CPU should be in use.</value>
        [DataMember(Name="targetPercentage", EmitDefaultValue=false)]
        public int? TargetPercentage { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1beta1CPUTargetUtilization {\n");
            sb.Append("  TargetPercentage: ").Append(TargetPercentage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as V1beta1CPUTargetUtilization);
        }

        /// <summary>
        /// Returns true if V1beta1CPUTargetUtilization instances are equal
        /// </summary>
        /// <param name="other">Instance of V1beta1CPUTargetUtilization to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1beta1CPUTargetUtilization other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TargetPercentage == other.TargetPercentage ||
                    this.TargetPercentage != null &&
                    this.TargetPercentage.Equals(other.TargetPercentage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TargetPercentage != null)
                    hash = hash * 59 + this.TargetPercentage.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
