/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using io.kubernetes.csharp.Client;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing ApisApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ApisApiTests
    {
        private ApisApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ApisApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApisApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ApisApi
            //Assert.IsInstanceOfType(typeof(ApisApi), instance, "instance is a ApisApi");
        }

        
        /// <summary>
        /// Test GetAPIVersions
        /// </summary>
        [Test]
        public void GetAPIVersionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAPIVersions();
            //Assert.IsInstanceOf<UnversionedAPIGroupList> (response, "response is UnversionedAPIGroupList");
        }
        
    }

}
