/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using io.kubernetes.csharp.Client;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing BatchV2alpha1Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BatchV2alpha1ApiTests
    {
        private BatchV2alpha1Api instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BatchV2alpha1Api();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchV2alpha1Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BatchV2alpha1Api
            //Assert.IsInstanceOfType(typeof(BatchV2alpha1Api), instance, "instance is a BatchV2alpha1Api");
        }

        
        /// <summary>
        /// Test CreateNamespacedCronJob
        /// </summary>
        [Test]
        public void CreateNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //V2alpha1CronJob body = null;
            //string pretty = null;
            //var response = instance.CreateNamespacedCronJob(_namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test CreateNamespacedJob
        /// </summary>
        [Test]
        public void CreateNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //V2alpha1Job body = null;
            //string pretty = null;
            //var response = instance.CreateNamespacedJob(_namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test CreateNamespacedScheduledJob
        /// </summary>
        [Test]
        public void CreateNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //V2alpha1CronJob body = null;
            //string pretty = null;
            //var response = instance.CreateNamespacedScheduledJob(_namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test DeleteCollectionNamespacedCronJob
        /// </summary>
        [Test]
        public void DeleteCollectionNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.DeleteCollectionNamespacedCronJob(_namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<UnversionedStatus> (response, "response is UnversionedStatus");
        }
        
        /// <summary>
        /// Test DeleteCollectionNamespacedJob
        /// </summary>
        [Test]
        public void DeleteCollectionNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.DeleteCollectionNamespacedJob(_namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<UnversionedStatus> (response, "response is UnversionedStatus");
        }
        
        /// <summary>
        /// Test DeleteCollectionNamespacedScheduledJob
        /// </summary>
        [Test]
        public void DeleteCollectionNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.DeleteCollectionNamespacedScheduledJob(_namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<UnversionedStatus> (response, "response is UnversionedStatus");
        }
        
        /// <summary>
        /// Test DeleteNamespacedCronJob
        /// </summary>
        [Test]
        public void DeleteNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1DeleteOptions body = null;
            //string pretty = null;
            //int? gracePeriodSeconds = null;
            //bool? orphanDependents = null;
            //var response = instance.DeleteNamespacedCronJob(name, _namespace, body, pretty, gracePeriodSeconds, orphanDependents);
            //Assert.IsInstanceOf<UnversionedStatus> (response, "response is UnversionedStatus");
        }
        
        /// <summary>
        /// Test DeleteNamespacedJob
        /// </summary>
        [Test]
        public void DeleteNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1DeleteOptions body = null;
            //string pretty = null;
            //int? gracePeriodSeconds = null;
            //bool? orphanDependents = null;
            //var response = instance.DeleteNamespacedJob(name, _namespace, body, pretty, gracePeriodSeconds, orphanDependents);
            //Assert.IsInstanceOf<UnversionedStatus> (response, "response is UnversionedStatus");
        }
        
        /// <summary>
        /// Test DeleteNamespacedScheduledJob
        /// </summary>
        [Test]
        public void DeleteNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1DeleteOptions body = null;
            //string pretty = null;
            //int? gracePeriodSeconds = null;
            //bool? orphanDependents = null;
            //var response = instance.DeleteNamespacedScheduledJob(name, _namespace, body, pretty, gracePeriodSeconds, orphanDependents);
            //Assert.IsInstanceOf<UnversionedStatus> (response, "response is UnversionedStatus");
        }
        
        /// <summary>
        /// Test GetAPIResources
        /// </summary>
        [Test]
        public void GetAPIResourcesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAPIResources();
            //Assert.IsInstanceOf<UnversionedAPIResourceList> (response, "response is UnversionedAPIResourceList");
        }
        
        /// <summary>
        /// Test ListCronJobForAllNamespaces
        /// </summary>
        [Test]
        public void ListCronJobForAllNamespacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fieldSelector = null;
            //string labelSelector = null;
            //string pretty = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListCronJobForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V2alpha1CronJobList> (response, "response is V2alpha1CronJobList");
        }
        
        /// <summary>
        /// Test ListJobForAllNamespaces
        /// </summary>
        [Test]
        public void ListJobForAllNamespacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fieldSelector = null;
            //string labelSelector = null;
            //string pretty = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListJobForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V2alpha1JobList> (response, "response is V2alpha1JobList");
        }
        
        /// <summary>
        /// Test ListNamespacedCronJob
        /// </summary>
        [Test]
        public void ListNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListNamespacedCronJob(_namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V2alpha1CronJobList> (response, "response is V2alpha1CronJobList");
        }
        
        /// <summary>
        /// Test ListNamespacedJob
        /// </summary>
        [Test]
        public void ListNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListNamespacedJob(_namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V2alpha1JobList> (response, "response is V2alpha1JobList");
        }
        
        /// <summary>
        /// Test ListNamespacedScheduledJob
        /// </summary>
        [Test]
        public void ListNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListNamespacedScheduledJob(_namespace, pretty, fieldSelector, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V2alpha1CronJobList> (response, "response is V2alpha1CronJobList");
        }
        
        /// <summary>
        /// Test ListScheduledJobForAllNamespaces
        /// </summary>
        [Test]
        public void ListScheduledJobForAllNamespacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fieldSelector = null;
            //string labelSelector = null;
            //string pretty = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListScheduledJobForAllNamespaces(fieldSelector, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V2alpha1CronJobList> (response, "response is V2alpha1CronJobList");
        }
        
        /// <summary>
        /// Test PatchNamespacedCronJob
        /// </summary>
        [Test]
        public void PatchNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //UnversionedPatch body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedCronJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test PatchNamespacedCronJobStatus
        /// </summary>
        [Test]
        public void PatchNamespacedCronJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //UnversionedPatch body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedCronJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test PatchNamespacedJob
        /// </summary>
        [Test]
        public void PatchNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //UnversionedPatch body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test PatchNamespacedJobStatus
        /// </summary>
        [Test]
        public void PatchNamespacedJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //UnversionedPatch body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test PatchNamespacedScheduledJob
        /// </summary>
        [Test]
        public void PatchNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //UnversionedPatch body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedScheduledJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test PatchNamespacedScheduledJobStatus
        /// </summary>
        [Test]
        public void PatchNamespacedScheduledJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //UnversionedPatch body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedScheduledJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReadNamespacedCronJob
        /// </summary>
        [Test]
        public void ReadNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //bool? exact = null;
            //bool? export = null;
            //var response = instance.ReadNamespacedCronJob(name, _namespace, pretty, exact, export);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReadNamespacedCronJobStatus
        /// </summary>
        [Test]
        public void ReadNamespacedCronJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //var response = instance.ReadNamespacedCronJobStatus(name, _namespace, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReadNamespacedJob
        /// </summary>
        [Test]
        public void ReadNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //bool? exact = null;
            //bool? export = null;
            //var response = instance.ReadNamespacedJob(name, _namespace, pretty, exact, export);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test ReadNamespacedJobStatus
        /// </summary>
        [Test]
        public void ReadNamespacedJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //var response = instance.ReadNamespacedJobStatus(name, _namespace, pretty);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test ReadNamespacedScheduledJob
        /// </summary>
        [Test]
        public void ReadNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //bool? exact = null;
            //bool? export = null;
            //var response = instance.ReadNamespacedScheduledJob(name, _namespace, pretty, exact, export);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReadNamespacedScheduledJobStatus
        /// </summary>
        [Test]
        public void ReadNamespacedScheduledJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //var response = instance.ReadNamespacedScheduledJobStatus(name, _namespace, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedCronJob
        /// </summary>
        [Test]
        public void ReplaceNamespacedCronJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V2alpha1CronJob body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedCronJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedCronJobStatus
        /// </summary>
        [Test]
        public void ReplaceNamespacedCronJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V2alpha1CronJob body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedCronJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedJob
        /// </summary>
        [Test]
        public void ReplaceNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V2alpha1Job body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedJobStatus
        /// </summary>
        [Test]
        public void ReplaceNamespacedJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V2alpha1Job body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1Job> (response, "response is V2alpha1Job");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedScheduledJob
        /// </summary>
        [Test]
        public void ReplaceNamespacedScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V2alpha1CronJob body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedScheduledJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedScheduledJobStatus
        /// </summary>
        [Test]
        public void ReplaceNamespacedScheduledJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V2alpha1CronJob body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedScheduledJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V2alpha1CronJob> (response, "response is V2alpha1CronJob");
        }
        
    }

}
