/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing RuntimeRawExtension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuntimeRawExtensionTests
    {
        // TODO uncomment below to declare an instance variable for RuntimeRawExtension
        //private RuntimeRawExtension instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuntimeRawExtension
            //instance = new RuntimeRawExtension();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuntimeRawExtension
        /// </summary>
        [Test]
        public void RuntimeRawExtensionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RuntimeRawExtension
            //Assert.IsInstanceOfType<RuntimeRawExtension> (instance, "variable 'instance' is a RuntimeRawExtension");
        }

        /// <summary>
        /// Test the property 'Raw'
        /// </summary>
        [Test]
        public void RawTest()
        {
            // TODO unit test for the property 'Raw'
        }

    }

}
