/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing UnversionedStatusDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UnversionedStatusDetailsTests
    {
        // TODO uncomment below to declare an instance variable for UnversionedStatusDetails
        //private UnversionedStatusDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UnversionedStatusDetails
            //instance = new UnversionedStatusDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UnversionedStatusDetails
        /// </summary>
        [Test]
        public void UnversionedStatusDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UnversionedStatusDetails
            //Assert.IsInstanceOfType<UnversionedStatusDetails> (instance, "variable 'instance' is a UnversionedStatusDetails");
        }

        /// <summary>
        /// Test the property 'Causes'
        /// </summary>
        [Test]
        public void CausesTest()
        {
            // TODO unit test for the property 'Causes'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RetryAfterSeconds'
        /// </summary>
        [Test]
        public void RetryAfterSecondsTest()
        {
            // TODO unit test for the property 'RetryAfterSeconds'
        }

    }

}
