/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing UnversionedAPIGroupList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UnversionedAPIGroupListTests
    {
        // TODO uncomment below to declare an instance variable for UnversionedAPIGroupList
        //private UnversionedAPIGroupList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UnversionedAPIGroupList
            //instance = new UnversionedAPIGroupList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UnversionedAPIGroupList
        /// </summary>
        [Test]
        public void UnversionedAPIGroupListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UnversionedAPIGroupList
            //Assert.IsInstanceOfType<UnversionedAPIGroupList> (instance, "variable 'instance' is a UnversionedAPIGroupList");
        }

        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Test]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

    }

}
