/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing UnversionedAPIResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UnversionedAPIResourceTests
    {
        // TODO uncomment below to declare an instance variable for UnversionedAPIResource
        //private UnversionedAPIResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UnversionedAPIResource
            //instance = new UnversionedAPIResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UnversionedAPIResource
        /// </summary>
        [Test]
        public void UnversionedAPIResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UnversionedAPIResource
            //Assert.IsInstanceOfType<UnversionedAPIResource> (instance, "variable 'instance' is a UnversionedAPIResource");
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Namespaced'
        /// </summary>
        [Test]
        public void NamespacedTest()
        {
            // TODO unit test for the property 'Namespaced'
        }

    }

}
