/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1alpha1PolicyRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1alpha1PolicyRuleTests
    {
        // TODO uncomment below to declare an instance variable for V1alpha1PolicyRule
        //private V1alpha1PolicyRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1alpha1PolicyRule
            //instance = new V1alpha1PolicyRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1alpha1PolicyRule
        /// </summary>
        [Test]
        public void V1alpha1PolicyRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1alpha1PolicyRule
            //Assert.IsInstanceOfType<V1alpha1PolicyRule> (instance, "variable 'instance' is a V1alpha1PolicyRule");
        }

        /// <summary>
        /// Test the property 'ApiGroups'
        /// </summary>
        [Test]
        public void ApiGroupsTest()
        {
            // TODO unit test for the property 'ApiGroups'
        }
        /// <summary>
        /// Test the property 'AttributeRestrictions'
        /// </summary>
        [Test]
        public void AttributeRestrictionsTest()
        {
            // TODO unit test for the property 'AttributeRestrictions'
        }
        /// <summary>
        /// Test the property 'NonResourceURLs'
        /// </summary>
        [Test]
        public void NonResourceURLsTest()
        {
            // TODO unit test for the property 'NonResourceURLs'
        }
        /// <summary>
        /// Test the property 'ResourceNames'
        /// </summary>
        [Test]
        public void ResourceNamesTest()
        {
            // TODO unit test for the property 'ResourceNames'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Verbs'
        /// </summary>
        [Test]
        public void VerbsTest()
        {
            // TODO unit test for the property 'Verbs'
        }

    }

}
