/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1beta1DeploymentStrategy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1DeploymentStrategyTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1DeploymentStrategy
        //private V1beta1DeploymentStrategy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1DeploymentStrategy
            //instance = new V1beta1DeploymentStrategy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1DeploymentStrategy
        /// </summary>
        [Test]
        public void V1beta1DeploymentStrategyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1DeploymentStrategy
            //Assert.IsInstanceOfType<V1beta1DeploymentStrategy> (instance, "variable 'instance' is a V1beta1DeploymentStrategy");
        }

        /// <summary>
        /// Test the property 'RollingUpdate'
        /// </summary>
        [Test]
        public void RollingUpdateTest()
        {
            // TODO unit test for the property 'RollingUpdate'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
