/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1beta1DeploymentCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1DeploymentConditionTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1DeploymentCondition
        //private V1beta1DeploymentCondition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1DeploymentCondition
            //instance = new V1beta1DeploymentCondition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1DeploymentCondition
        /// </summary>
        [Test]
        public void V1beta1DeploymentConditionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1DeploymentCondition
            //Assert.IsInstanceOfType<V1beta1DeploymentCondition> (instance, "variable 'instance' is a V1beta1DeploymentCondition");
        }

        /// <summary>
        /// Test the property 'LastTransitionTime'
        /// </summary>
        [Test]
        public void LastTransitionTimeTest()
        {
            // TODO unit test for the property 'LastTransitionTime'
        }
        /// <summary>
        /// Test the property 'LastUpdateTime'
        /// </summary>
        [Test]
        public void LastUpdateTimeTest()
        {
            // TODO unit test for the property 'LastUpdateTime'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
