/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1beta1DeploymentSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1DeploymentSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1DeploymentSpec
        //private V1beta1DeploymentSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1DeploymentSpec
            //instance = new V1beta1DeploymentSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1DeploymentSpec
        /// </summary>
        [Test]
        public void V1beta1DeploymentSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1DeploymentSpec
            //Assert.IsInstanceOfType<V1beta1DeploymentSpec> (instance, "variable 'instance' is a V1beta1DeploymentSpec");
        }

        /// <summary>
        /// Test the property 'MinReadySeconds'
        /// </summary>
        [Test]
        public void MinReadySecondsTest()
        {
            // TODO unit test for the property 'MinReadySeconds'
        }
        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Test]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }
        /// <summary>
        /// Test the property 'ProgressDeadlineSeconds'
        /// </summary>
        [Test]
        public void ProgressDeadlineSecondsTest()
        {
            // TODO unit test for the property 'ProgressDeadlineSeconds'
        }
        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }
        /// <summary>
        /// Test the property 'RevisionHistoryLimit'
        /// </summary>
        [Test]
        public void RevisionHistoryLimitTest()
        {
            // TODO unit test for the property 'RevisionHistoryLimit'
        }
        /// <summary>
        /// Test the property 'RollbackTo'
        /// </summary>
        [Test]
        public void RollbackToTest()
        {
            // TODO unit test for the property 'RollbackTo'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Test]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
