/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1beta1DaemonSetStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1DaemonSetStatusTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1DaemonSetStatus
        //private V1beta1DaemonSetStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1DaemonSetStatus
            //instance = new V1beta1DaemonSetStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1DaemonSetStatus
        /// </summary>
        [Test]
        public void V1beta1DaemonSetStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1DaemonSetStatus
            //Assert.IsInstanceOfType<V1beta1DaemonSetStatus> (instance, "variable 'instance' is a V1beta1DaemonSetStatus");
        }

        /// <summary>
        /// Test the property 'CurrentNumberScheduled'
        /// </summary>
        [Test]
        public void CurrentNumberScheduledTest()
        {
            // TODO unit test for the property 'CurrentNumberScheduled'
        }
        /// <summary>
        /// Test the property 'DesiredNumberScheduled'
        /// </summary>
        [Test]
        public void DesiredNumberScheduledTest()
        {
            // TODO unit test for the property 'DesiredNumberScheduled'
        }
        /// <summary>
        /// Test the property 'NumberMisscheduled'
        /// </summary>
        [Test]
        public void NumberMisscheduledTest()
        {
            // TODO unit test for the property 'NumberMisscheduled'
        }
        /// <summary>
        /// Test the property 'NumberReady'
        /// </summary>
        [Test]
        public void NumberReadyTest()
        {
            // TODO unit test for the property 'NumberReady'
        }

    }

}
