/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1beta1JobSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1JobSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1JobSpec
        //private V1beta1JobSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1JobSpec
            //instance = new V1beta1JobSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1JobSpec
        /// </summary>
        [Test]
        public void V1beta1JobSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1JobSpec
            //Assert.IsInstanceOfType<V1beta1JobSpec> (instance, "variable 'instance' is a V1beta1JobSpec");
        }

        /// <summary>
        /// Test the property 'ActiveDeadlineSeconds'
        /// </summary>
        [Test]
        public void ActiveDeadlineSecondsTest()
        {
            // TODO unit test for the property 'ActiveDeadlineSeconds'
        }
        /// <summary>
        /// Test the property 'AutoSelector'
        /// </summary>
        [Test]
        public void AutoSelectorTest()
        {
            // TODO unit test for the property 'AutoSelector'
        }
        /// <summary>
        /// Test the property 'Completions'
        /// </summary>
        [Test]
        public void CompletionsTest()
        {
            // TODO unit test for the property 'Completions'
        }
        /// <summary>
        /// Test the property 'Parallelism'
        /// </summary>
        [Test]
        public void ParallelismTest()
        {
            // TODO unit test for the property 'Parallelism'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
