/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1ConfigMapVolumeSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ConfigMapVolumeSourceTests
    {
        // TODO uncomment below to declare an instance variable for V1ConfigMapVolumeSource
        //private V1ConfigMapVolumeSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ConfigMapVolumeSource
            //instance = new V1ConfigMapVolumeSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ConfigMapVolumeSource
        /// </summary>
        [Test]
        public void V1ConfigMapVolumeSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ConfigMapVolumeSource
            //Assert.IsInstanceOfType<V1ConfigMapVolumeSource> (instance, "variable 'instance' is a V1ConfigMapVolumeSource");
        }

        /// <summary>
        /// Test the property 'DefaultMode'
        /// </summary>
        [Test]
        public void DefaultModeTest()
        {
            // TODO unit test for the property 'DefaultMode'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
