/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1Handler
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1HandlerTests
    {
        // TODO uncomment below to declare an instance variable for V1Handler
        //private V1Handler instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1Handler
            //instance = new V1Handler();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1Handler
        /// </summary>
        [Test]
        public void V1HandlerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1Handler
            //Assert.IsInstanceOfType<V1Handler> (instance, "variable 'instance' is a V1Handler");
        }

        /// <summary>
        /// Test the property 'Exec'
        /// </summary>
        [Test]
        public void ExecTest()
        {
            // TODO unit test for the property 'Exec'
        }
        /// <summary>
        /// Test the property 'HttpGet'
        /// </summary>
        [Test]
        public void HttpGetTest()
        {
            // TODO unit test for the property 'HttpGet'
        }
        /// <summary>
        /// Test the property 'TcpSocket'
        /// </summary>
        [Test]
        public void TcpSocketTest()
        {
            // TODO unit test for the property 'TcpSocket'
        }

    }

}
