/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1NFSVolumeSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1NFSVolumeSourceTests
    {
        // TODO uncomment below to declare an instance variable for V1NFSVolumeSource
        //private V1NFSVolumeSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1NFSVolumeSource
            //instance = new V1NFSVolumeSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1NFSVolumeSource
        /// </summary>
        [Test]
        public void V1NFSVolumeSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1NFSVolumeSource
            //Assert.IsInstanceOfType<V1NFSVolumeSource> (instance, "variable 'instance' is a V1NFSVolumeSource");
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property '_ReadOnly'
        /// </summary>
        [Test]
        public void _ReadOnlyTest()
        {
            // TODO unit test for the property '_ReadOnly'
        }
        /// <summary>
        /// Test the property 'Server'
        /// </summary>
        [Test]
        public void ServerTest()
        {
            // TODO unit test for the property 'Server'
        }

    }

}
