/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1NodeSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1NodeSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1NodeSpec
        //private V1NodeSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1NodeSpec
            //instance = new V1NodeSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1NodeSpec
        /// </summary>
        [Test]
        public void V1NodeSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1NodeSpec
            //Assert.IsInstanceOfType<V1NodeSpec> (instance, "variable 'instance' is a V1NodeSpec");
        }

        /// <summary>
        /// Test the property 'ExternalID'
        /// </summary>
        [Test]
        public void ExternalIDTest()
        {
            // TODO unit test for the property 'ExternalID'
        }
        /// <summary>
        /// Test the property 'PodCIDR'
        /// </summary>
        [Test]
        public void PodCIDRTest()
        {
            // TODO unit test for the property 'PodCIDR'
        }
        /// <summary>
        /// Test the property 'ProviderID'
        /// </summary>
        [Test]
        public void ProviderIDTest()
        {
            // TODO unit test for the property 'ProviderID'
        }
        /// <summary>
        /// Test the property 'Unschedulable'
        /// </summary>
        [Test]
        public void UnschedulableTest()
        {
            // TODO unit test for the property 'Unschedulable'
        }

    }

}
