/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1NodeDaemonEndpoints
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1NodeDaemonEndpointsTests
    {
        // TODO uncomment below to declare an instance variable for V1NodeDaemonEndpoints
        //private V1NodeDaemonEndpoints instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1NodeDaemonEndpoints
            //instance = new V1NodeDaemonEndpoints();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1NodeDaemonEndpoints
        /// </summary>
        [Test]
        public void V1NodeDaemonEndpointsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1NodeDaemonEndpoints
            //Assert.IsInstanceOfType<V1NodeDaemonEndpoints> (instance, "variable 'instance' is a V1NodeDaemonEndpoints");
        }

        /// <summary>
        /// Test the property 'KubeletEndpoint'
        /// </summary>
        [Test]
        public void KubeletEndpointTest()
        {
            // TODO unit test for the property 'KubeletEndpoint'
        }

    }

}
