/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1PersistentVolumeClaimSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1PersistentVolumeClaimSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1PersistentVolumeClaimSpec
        //private V1PersistentVolumeClaimSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PersistentVolumeClaimSpec
            //instance = new V1PersistentVolumeClaimSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PersistentVolumeClaimSpec
        /// </summary>
        [Test]
        public void V1PersistentVolumeClaimSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1PersistentVolumeClaimSpec
            //Assert.IsInstanceOfType<V1PersistentVolumeClaimSpec> (instance, "variable 'instance' is a V1PersistentVolumeClaimSpec");
        }

        /// <summary>
        /// Test the property 'AccessModes'
        /// </summary>
        [Test]
        public void AccessModesTest()
        {
            // TODO unit test for the property 'AccessModes'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'VolumeName'
        /// </summary>
        [Test]
        public void VolumeNameTest()
        {
            // TODO unit test for the property 'VolumeName'
        }

    }

}
