/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1PodSecurityContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1PodSecurityContextTests
    {
        // TODO uncomment below to declare an instance variable for V1PodSecurityContext
        //private V1PodSecurityContext instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PodSecurityContext
            //instance = new V1PodSecurityContext();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PodSecurityContext
        /// </summary>
        [Test]
        public void V1PodSecurityContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1PodSecurityContext
            //Assert.IsInstanceOfType<V1PodSecurityContext> (instance, "variable 'instance' is a V1PodSecurityContext");
        }

        /// <summary>
        /// Test the property 'FsGroup'
        /// </summary>
        [Test]
        public void FsGroupTest()
        {
            // TODO unit test for the property 'FsGroup'
        }
        /// <summary>
        /// Test the property 'RunAsNonRoot'
        /// </summary>
        [Test]
        public void RunAsNonRootTest()
        {
            // TODO unit test for the property 'RunAsNonRoot'
        }
        /// <summary>
        /// Test the property 'RunAsUser'
        /// </summary>
        [Test]
        public void RunAsUserTest()
        {
            // TODO unit test for the property 'RunAsUser'
        }
        /// <summary>
        /// Test the property 'SeLinuxOptions'
        /// </summary>
        [Test]
        public void SeLinuxOptionsTest()
        {
            // TODO unit test for the property 'SeLinuxOptions'
        }
        /// <summary>
        /// Test the property 'SupplementalGroups'
        /// </summary>
        [Test]
        public void SupplementalGroupsTest()
        {
            // TODO unit test for the property 'SupplementalGroups'
        }

    }

}
