/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1ResourceFieldSelector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ResourceFieldSelectorTests
    {
        // TODO uncomment below to declare an instance variable for V1ResourceFieldSelector
        //private V1ResourceFieldSelector instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ResourceFieldSelector
            //instance = new V1ResourceFieldSelector();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ResourceFieldSelector
        /// </summary>
        [Test]
        public void V1ResourceFieldSelectorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ResourceFieldSelector
            //Assert.IsInstanceOfType<V1ResourceFieldSelector> (instance, "variable 'instance' is a V1ResourceFieldSelector");
        }

        /// <summary>
        /// Test the property 'ContainerName'
        /// </summary>
        [Test]
        public void ContainerNameTest()
        {
            // TODO unit test for the property 'ContainerName'
        }
        /// <summary>
        /// Test the property 'Divisor'
        /// </summary>
        [Test]
        public void DivisorTest()
        {
            // TODO unit test for the property 'Divisor'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }

    }

}
