/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1ScaleSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ScaleSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1ScaleSpec
        //private V1ScaleSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ScaleSpec
            //instance = new V1ScaleSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ScaleSpec
        /// </summary>
        [Test]
        public void V1ScaleSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ScaleSpec
            //Assert.IsInstanceOfType<V1ScaleSpec> (instance, "variable 'instance' is a V1ScaleSpec");
        }

        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }

    }

}
