/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1ServiceSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ServiceSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1ServiceSpec
        //private V1ServiceSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ServiceSpec
            //instance = new V1ServiceSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ServiceSpec
        /// </summary>
        [Test]
        public void V1ServiceSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ServiceSpec
            //Assert.IsInstanceOfType<V1ServiceSpec> (instance, "variable 'instance' is a V1ServiceSpec");
        }

        /// <summary>
        /// Test the property 'ClusterIP'
        /// </summary>
        [Test]
        public void ClusterIPTest()
        {
            // TODO unit test for the property 'ClusterIP'
        }
        /// <summary>
        /// Test the property 'DeprecatedPublicIPs'
        /// </summary>
        [Test]
        public void DeprecatedPublicIPsTest()
        {
            // TODO unit test for the property 'DeprecatedPublicIPs'
        }
        /// <summary>
        /// Test the property 'ExternalIPs'
        /// </summary>
        [Test]
        public void ExternalIPsTest()
        {
            // TODO unit test for the property 'ExternalIPs'
        }
        /// <summary>
        /// Test the property 'ExternalName'
        /// </summary>
        [Test]
        public void ExternalNameTest()
        {
            // TODO unit test for the property 'ExternalName'
        }
        /// <summary>
        /// Test the property 'LoadBalancerIP'
        /// </summary>
        [Test]
        public void LoadBalancerIPTest()
        {
            // TODO unit test for the property 'LoadBalancerIP'
        }
        /// <summary>
        /// Test the property 'LoadBalancerSourceRanges'
        /// </summary>
        [Test]
        public void LoadBalancerSourceRangesTest()
        {
            // TODO unit test for the property 'LoadBalancerSourceRanges'
        }
        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Test]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'SessionAffinity'
        /// </summary>
        [Test]
        public void SessionAffinityTest()
        {
            // TODO unit test for the property 'SessionAffinity'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
