/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1SELinuxOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1SELinuxOptionsTests
    {
        // TODO uncomment below to declare an instance variable for V1SELinuxOptions
        //private V1SELinuxOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1SELinuxOptions
            //instance = new V1SELinuxOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1SELinuxOptions
        /// </summary>
        [Test]
        public void V1SELinuxOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1SELinuxOptions
            //Assert.IsInstanceOfType<V1SELinuxOptions> (instance, "variable 'instance' is a V1SELinuxOptions");
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
