/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.kubernetes.csharp.Api;
using io.kubernetes.csharp.Model;
using io.kubernetes.csharp.Client;
using System.Reflection;

namespace io.kubernetes.csharp.Test
{
    /// <summary>
    ///  Class for testing V1VolumeMount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1VolumeMountTests
    {
        // TODO uncomment below to declare an instance variable for V1VolumeMount
        //private V1VolumeMount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1VolumeMount
            //instance = new V1VolumeMount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1VolumeMount
        /// </summary>
        [Test]
        public void V1VolumeMountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1VolumeMount
            //Assert.IsInstanceOfType<V1VolumeMount> (instance, "variable 'instance' is a V1VolumeMount");
        }

        /// <summary>
        /// Test the property 'MountPath'
        /// </summary>
        [Test]
        public void MountPathTest()
        {
            // TODO unit test for the property 'MountPath'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_ReadOnly'
        /// </summary>
        [Test]
        public void _ReadOnlyTest()
        {
            // TODO unit test for the property '_ReadOnly'
        }
        /// <summary>
        /// Test the property 'SubPath'
        /// </summary>
        [Test]
        public void SubPathTest()
        {
            // TODO unit test for the property 'SubPath'
        }

    }

}
